### ISSUE TITLE
Version should be the same as upstream

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/libretro-gme#1]
info->library_version should be the same as upstream (Game_Music_Emu 0.6.1 right?)

**Comment by sergiobenrocha2** [comment]
Btw, great work!

**Comment by larrykoubiak** [comment]
Thanks for the feedback, should be ok now.
Valeu! ;)

**Comment by sergiobenrocha2** [comment]
An wild Brazilian appeared \o/
